-- A whole plugin. It declares one toolchain, and that toolchain generates one
-- file from the manifest.
--
-- daukle.plugin MUST be the first call in the chunk: the pre-pass that reads
-- "uses" runs before anything else, and a daukle.require above this line is
-- refused rather than silently allowed.
daukle.plugin{ api = 1, uses = {} }

daukle.toolchain{
  name = "banner",
  -- generate is a PURE function of the manifest. It may not call exec or tool,
  -- because "daukle check" runs it and check must never start your compiler.
  -- It returns a table of relative path to file text, and daukle does every
  -- write, which is why the sandbox has no write verb at all.
  generate = function(context)
    -- In generate the block is context.config; in a TASK the same block is
    -- context.toolchain.config. Real plugins keep a one line config_of helper
    -- so the two cannot be confused.
    local config = context.config
    local greeting = config.greeting or "hello"
    local lines = {
      "/* Generated by the banner toolchain. Do not edit. */",
      '#define BANNER "' .. greeting .. ' from ' .. context.project .. '"',
      '#define BANNER_VERSION "' .. context.version .. '"',
    }
    return { ["banner.h"] = table.concat(lines, "\n") .. "\n" }
  end,
}
